### ISSUE TITLE
Mod doens't load?

### ISSUE THREAD

**Issue by MarcHagen** [Towdium/JustEnoughCalculation#12]
http://paste.feed-the-beast.com/view/49460766

`[21:53:51] [Client thread/INFO] [FML]:   Unknown recipe class! pers.towdium.justEnoughCalculation.JustEnoughCalculation$1 Modder please refer to net.minecraftforge.oredict.RecipeSorter`

FTB Inventions 1.0.1 - MC 1.7.10 - Java 1.8

**Comment by Towdium** [comment]
Thanks for report!

I'm sorry to say I have just tested this issue on the same pack but it loads fine since I can still find the calculator item although I have similar console output.
I will check if there are ways to avoid this warning but it should effect the loading of the mod.
Try download the pack again, it should possibly solve the problem.
You can see the issue here #10

**Comment by Towdium** [comment]
I will temporarily close this issue since it has gone pretty far.
If you have further information, open it again.
