### ISSUE TITLE
Quantities don't show on items.

### ISSUE THREAD

**Issue by Fokson** [Towdium/JustEnoughCalculation#14]
http://puu.sh/raE9R/e78821f60d.png

The quantities ARE recognized; if I have three of the four electrical steel I need it will still say I'm missing an electrical steel.  However, when I'm missing 4 electrical steel, or when looking at the total cost of an item on any part of the GUI, it never shows the quantity of an item.

Minecraft 1.10.2
JEC 2.0.1

Any more info needed, let me know!

**Comment by Towdium** [comment]
Thanks for reporting!

Actually if the amount is 1, it should display "1" instead of the way vanilla minecraft do, so it happens possibly because the hacking procedure does not work correctly and all of the amount render is broken. If you want to know more, the stack size of all the itemstacks displayed is 1, the amount data is stored in NBT data and I use an alternate way to render it.

Currently I can not reproduce this bug in every environment I'm using. But this could most possibly happen when you are using some coremod that changes the vanilla way of rendering a GUI. Just Enough Calculation inserts everything in the method `setWorldAndResolution` of `GuiContainer`, so if this method is not invoked, the insertion will not be done.

From my personal view, this should be a mod conflicting issue. So can you firstly test if it works correctly in vanilla minecraft on your computer. If there is nothing wrong, can you try to figure out which mod is conflicting. As is said ahead, it should most possibly be coremods (like NEI? but NEI seems don't have 1.10 version ). If it is difficult for you, you can provide the modlist you are using and I will find some time to test it.

**Comment by Fokson** [comment]
I do have a fairly extensive modlist at present, so I'll do a little experimentation and find out what's causing it if I can.

---

That was a very short test.  It turns out there IS an NEI for 1.10, and I do have it installed.  JEC failed to show any item quantities with no other mods installed besides JEI, NEI and CodeChickenCore.

NEI version/filename: NotEnoughItems-1.10.2-2.1.1.147-universal
CCC version/filename: CodeChickenCore-1.10.2-2.1.8.79-universal
Download page: http://chickenbones.net/Pages/links.html

**Comment by Towdium** [comment]
Oops! Trying to keep compatibility with NEI might be the worst thing I could imagine since it changes really some of vanilla behavior and make it difficult to fix. Luckly I have got some experience when doing 1.7.10. I will try to fix it.

BTW, can you briefly tell me what will NEI do when you have JEI installed? I'm not very familiar with the 1.10 version of it.

**Comment by Fokson** [comment]
Simply put, it adds the rest of what NEI did from 1.7.10: buttons on the left for saving inventory layouts, setting time, all that good stuff. I actually didn't realize that JEI did everything that was most important, and installed it primarily because NEI required it as a prerequisite. I removed NEI to get JEC to work, and haven't really missed it since. 

It also seems to add a small and simple WAILA window, telling you what block you're looking at.

**Comment by Towdium** [comment]
Thx for telling me this.
By the way, you can simply use ftb utilities to add the buttons at upper left back. There are also some substitution for the WAILA window.
But will try to fix the compatibility.

**Comment by Fokson** [comment]
Yeah, I'm not too worried about it. I do my best to stay on the straight-and-narrow when I play survival =P  Glad I could be of assistance!
