### ISSUE TITLE
Nutrition Module in Crafting Calc

### ISSUE THREAD

**Issue by DFliyerz** [Towdium/JustEnoughCalculation#15]
The Nutrition Module from the Calculator mod keeps showing up in random slots in the Crafting Calculator, and clicking it too much causes a crash.
http://pastebin.com/wL1n8mB1

Edit: Another crash, this time when trying to save a recipe. http://pastebin.com/Fak9399Q

**Comment by Towdium** [comment]
Thanks for report!

For the item rendering issue, actually it has been reported about half a year ago #6 , but it seems to happen not frequently and I myself am trying to reproduce it but didn't succeed. I have been will continue trying to locate the problem but I cannot promise to fix it very soon.

For the second crash, it seems more like a bug caused by my poor coding. Can you describe more about it? What's the recipe like? Does it crash for every recipe or just certain recipes?

**Comment by DFliyerz** [comment]
It was the recipe for the Calculator Plug from the Calculator mod.

**Comment by Towdium** [comment]
Ok, I will test it.

**Comment by Towdium** [comment]
Now the nutrition module problem has been fixed but I'm not able to reproduce the crash when saving the recipe. This issue has been moved to #18 , you can keep an eye on it.
