### ISSUE TITLE
CRASHes when open recipe calculator

### ISSUE THREAD

**Issue by MarikCZ** [Towdium/JustEnoughCalculation#28]
Yesterday, I searched for materials needed to craft EnderIO Vibrant Capacitor Bank. All was right.
Today, I try to open Calculator (recipe) and game freezes on few seconds, and after crashes.
I'm tried to do, on PC of my brother. I set recipe, and all was right. But when I tried to edit, it did same thing - game freezes on few seconds, and after crashes.

Maybe mistake is there:
CPU: 2x AMD Athlon(tm) II X2 215 Processor   (It work on 100% when game freezes.)

[There](http://pastebin.com/L9Fs6iZy) is Crash-Report too.

**Comment by Towdium** [comment]
Thanks for reporting.

### General description

I think I have to say it's a pretty wired problem and I currently have no idea how to reproduce it. I think it should be more like a programming issue rather than hardware issue. If there is infinite loop, there should be clues in the crash report while none can be found. I think for most of reasons when minecraft crashes, there is a short freeze and 100% CPU usage since minecraft is saving the user data and generating crash report. This is the built-in mechanic to deal with exceptions. 

In the crash report it says the exception happens at the method "onGuiClosed", aka "func_146281_b", which should be invoked when closing the GUI, but you said it crashes when opening the calculator. This might be some coremod doing some hack here or for some other unknown reason.

### For further investigation

- Does it happens every time or occasionally? Since this should be a common way to use it and I have received no report about it.
- Can you state the steps to reproduce the issue in detail? Better with a newly created empty world.
- Which version of JEC are you using?
- Did you have any mod list change before the crash happens? especially adding coremods?
- If it is convenient, can you send me the crash report on your brother's PC as well?
- If you are using curse client, maybe you can generate a file to share the modpack you are using to me. Otherwise maybe you can provide the minimum mod list to reproduce the problem to me.
- May be you can send me your JEC player record? There is no personal information in this file, just you JEC records. It should locate at `%save_directory%/playerdata/%uuid%.jeca`.

By the way, I think you can directly upload the file through github by drag and drop. This might save you some time especially when it is not pure text.

**Comment by MarikCZ** [comment]
- It happens every time at calculator open. But there is other causes thats make same thing - for example, viewing Centrifuge recipes of mod TechReborn. (Freezes only Client, Server not.)
- Soon.
- Newest version (I use Curse-Client)
- I don't know. I use JEC yesterday at first time. And currently version of this pack is only 3 days old.
- I'm so sorry - I don't know why but crash-reports generates only sometimes. I have only one (my) crash-report but minecraft crashes totally by 8x!
- Yes, but I don't know how I can upload it on github (where).
- Soon.

**Comment by MarikCZ** [comment]
And [there](http://pastebin.com/k78scjcY) is brother's crash-report.

**Comment by Towdium** [comment]
Just don't be sorry for no crash report, actually I should be sorry for the crashes. There will be no crash report if minecraft fails to catch the exception, you can upload the log instead, they should locate at the logs directory. You can distinguish them by the time generated. The log should contain everything. It seems the crash report you uploaded just now is the same as the first one. Maybe the logs may have different information. To upload files, just drag and drop the file from the explorer into the editor in the github page, it will automatically upload. If you want, you can select files as well. You can use the link "selecting them" in the picture I upload below, right at the bottom of the text editor.

![2017-01-22 15-54-06](https://cloud.githubusercontent.com/assets/10866568/22183664/1cef1956-e0bb-11e6-95dc-2e5befdf55bb.png)

And can I know which modpack are you using? Maybe I can download and do some test. By the way, I think this is most possibly a compatibility problem.

**Comment by MarikCZ** [comment]
OK, sure. I´m think, there is a problem in a lots of NBT tags in calculator - more recipes, more chance to crash. But it´s all.
[Pack of Marik's Pixels-2.0u2.zip](https://github.com/Towdium/JustEnoughCalculation/files/722057/Pack.of.Marik.s.Pixels-2.0u2.zip)

**Comment by Towdium** [comment]
Have tested on your pack and have no progress. For some reason the crash seems won't appear on my computer. But I have compiled a test version that is modified according to the crash report, to prevent the game to crash. Maybe you can give it a try.

[testjar.zip](https://github.com/Towdium/JustEnoughCalculation/files/722113/testjar.zip)

**Comment by MarikCZ** [comment]
Yeah, test version is 1000% stable. Its little bit laggy when opening or saving, but very small.
BTW: I found missing feature (files).
![2017-01-22_19 28 52](https://cloud.githubusercontent.com/assets/24923429/22184781/8ee37b1a-e0d9-11e6-9f48-01f84a71b793.png)
![2017-01-22_19 29 03](https://cloud.githubusercontent.com/assets/24923429/22184782/8ee3becc-e0d9-11e6-8140-ff9d18e87172.png)

But currently I have more problems with freezing other applications, so I think my CPU is KAPPING.. Not your JEC. :)

**Comment by Towdium** [comment]
That is good! The "+" button will appear the second time you launch minecraft. There is a little hack here while it is not easy to be noticed by most of users. Actually, running minecraft costs really some performance, even on some good PCs, the lagging of the system is still noticeable. This might be caused by JRE and openGL. From my personal experience, if you are using a linux PC, you will get a slight improvement on both FPS and system performance when running (but it's hard to configure).

**Comment by MarikCZ** [comment]
I try to use 2.4 version in vanila - CRASH. I try to use !test! version in the Vannila - very good. I try to use it in PoMP in flat world - good. I try to use it in my world - CRASH without crash-report.
Logs:

[logs.zip](https://github.com/Towdium/JustEnoughCalculation/files/724268/logs.zip)

But I more and more think the error is in my [machine](http://pastebin.com/3LxaTpNQ).

**Comment by Towdium** [comment]
It seems the log ends without any clue about the crash. Maybe you can try another test file, I'm just doing tweaks by guessing the error. In addition, you can try delete the JEC record file `%save_directory%/playerdata/%uuid%.jeca`. The picture shows the location of my record file. 

![2017-01-23 16-59-04](https://cloud.githubusercontent.com/assets/10866568/22213800/63faa892-e18d-11e6-9910-51ae444bae9d.png)

[test2.zip](https://github.com/Towdium/JustEnoughCalculation/files/724351/test2.zip)

**Comment by MarikCZ** [comment]
[playerdata.zip](https://github.com/Towdium/JustEnoughCalculation/files/724548/playerdata.zip)
OK. I going to try new version without playerdata.

**Comment by MarikCZ** [comment]
Works good. So when I save about 30 recipes, game freezes and... Crashes.
I have one idea, create some small modpack that contains about 30 most me prefered and fully stable mods (so without TechReborn), and try JEC by moretime. But I have some other work now, so tomorrow.
And happening at cause:
![snimek obrazovky 103](https://cloud.githubusercontent.com/assets/24923429/22217667/353676c8-e1a4-11e6-996e-1c849fc94a4c.png)
![snimek obrazovky 105](https://cloud.githubusercontent.com/assets/24923429/22217666/3533f5c4-e1a4-11e6-807d-6bcb27cd1e25.png)

**Comment by MarikCZ** [comment]
Crash-report was not generated again.
So there are log files.
[logs2.zip](https://github.com/Towdium/JustEnoughCalculation/files/724631/logs2.zip)

**Comment by Towdium** [comment]
Ok I can find some information this time. The log says the system is overloading, that might be the reason. Since I'm doing all the data related work in the main thread, I'm possibly pausing the thread for a pretty long time, making the game to freeze and causing other problems. Maybe I can load the information in another thread but I'm not familiar with those stuff and I don't have an old PC, so it might not be fixed in a short time. I'm sorry for that.

**Comment by MarikCZ** [comment]
Dear Towdium

Just don't be sorry for that! (as you said)
You are very good and conscientious developer, and this project is very good too. I have to account with the fact, that I have not the beefy computer, so I can not allow me to play with the more complex and sofisticated mods. - So, that is not your mistake.
I think that after this solution, is your mod just got better and more stable. Anyway, thank you very much for your support!

Good luck in the future of codding and modding.

Best regards

Marik

**Comment by Towdium** [comment]
My English is not good enough to express my emotion, but, many thanks.

**Comment by MarikCZ** [comment]
My English is not very good too - you are not alone in that. :D
