### ISSUE TITLE
[DONT WORK] 

### ISSUE THREAD

**Issue by SugarDaddii** [Towdium/JustEnoughCalculation#4]
**Minecraft 1.7.10 Multiplayer**

![dont work](https://cloud.githubusercontent.com/assets/14795020/13972002/18c244d2-f095-11e5-9415-5b21cf6b1820.jpg)

Hey me again when i try to calculate a item it doesnt let me click the button!

What iam doing wrong!?

**Comment by Towdium** [comment]
THX for report!
You should first record the recipe using Add button. After you have recipe recorded for the selected item, it will allow you to click the button. Recipe can be loaded by NEI's shift-'?'-click quickly in the recipe edit screen or you can record any custom recipes as you want.
Let me explain more about why it won't detect any recipe available to calculate. The reason is simple: there might be some recipes you don't want to use, and the mod will never know. So I choose to let  the user input the recipes they prefer. Another good thing is, you can input any combination you want, even they are not registerd in NEI, this can improve compatibility.
I will consider making a video to show how to use it.

**Comment by SugarDaddii** [comment]
OHH AHH! 
so first you should learn the mod every single crafting recipe before calculate it?

that why it doesnt work!

Yeah maybe do a tut about your mod...i will try it at home!

have a nice day

**Comment by Towdium** [comment]
I have updated a video in the description! (With funny English XD)
And by the way, just uploaded a new version to fix crash.
Have fun~
