### ISSUE TITLE
Any chance for support with Avaritia?

### ISSUE THREAD

**Issue by ryu777mtg** [Towdium/JustEnoughCalculation#40]
I'm using the mod with a relatively small testing pack to test out all the catalyst and options this mod has to offer.

Unfortunately say I want to add the Infinity Catalyst or any Item using the Dire Crafting Table there is no way to  add 81 items to the input field for the 9x9 table even tried breaking the recipe up using the item I wanted 3 times to get 36 items added to the recipe but it doesn't register but only 12 from one of the 3 entries.

Also using the latest versions for both mods on 1.10.2

**Comment by Towdium** [comment]
Thanks for the feedback!

Here's my suggestion: you can use the label system introduced in [this video](https://youtu.be/yRVedm5x3b4). The current system will not allow you to have that much inputs (mainly because complexity in GUI organization and data storage), but you can actually do it by cascating the labels.

For the variable input list, it is possible to be implemented after I finish the 1.12 rewrite.

**Comment by ryu777mtg** [comment]
When I nest the label inside the label should the labels have the same name? Or does it matter?

**Comment by Towdium** [comment]
Labels are basically fake items distinguished by names. Typically you can have the structure "destination item = label1  + label2", "label1 = list of items", "label2 = list of items". So for all the label1, they should have the same name, so do all the label2. But label1 and label2 should have different names.

The idea is if you want the system to consider them as same item, then use same name, otherwise not.

**Comment by Towdium** [comment]
It is supported in 1.14+. Recipes can have as many items now. But 1.12 is relatively an old version, so I will not add new things to it.
