### ISSUE TITLE
[1.7.10] Cannot import from NEI

### ISSUE THREAD

**Issue by HuJK** [Towdium/JustEnoughCalculation#52]
Use NEI's drag and drop interaction to choose items.
[Work] 

NEI's "?"-click is also supported. Use shift-click-"?" in recipe GUI for auto complete.
[I don't know what is this. what is 「?"-click 」?]

The key "R" to show recipe doesn't work in the Calculator GUI, use left click instead.
[Not Work, recipe shown but no "+" button so I can't import] 

Other things just work similarly as in 1.8.9 version.

**Comment by Towdium** [comment]
Thanks for report!

Well, that is such a long time ago, so 1.7.10 version will not get support and fixes because I can't really remember it myself. I'm sorry for that.

I'm quite sure that worked years ago. Just open up recipe editor, then open one recipe from NEI, the "+" button should be there, just like JEI. Then hold shift and click that "+" button, it will get transferred. 

I don't know if there is any updates in some mods that cause some compatibility problem. But what I can tell is it's always painful to support NEI, and I won't have time to look into it in months to come.

Again, sorry for the problem, but feel free to ask any questions.

**Comment by HuJK** [comment]
Ok, Thank your attention. I can import the recipe manually. 
: )
