### ISSUE TITLE
Client side doesnt work

### ISSUE THREAD

**Issue by MavDarkness** [Towdium/JustEnoughCalculation#56]
having a mod be client side only should mean that you can put it in your modpack and join a server(which doesnt have it) and all would be fine and swell. this is not the case as i tested for enigmatica 2 expert mode. installed mod, tried to join a dedicated multiplayer server. i get timed out every time. client mode is enabled in configs.

**Comment by Towdium** [comment]
Thanks for report!

Yes it's expected to join any server with this mod. I'm not sure if there is any change in forge that breaks it or any compatibility issue. I will check it.

**Comment by MavDarkness** [comment]
has there been any progress with this? to be frank id throw away all server communication in this mod and just make it client side....

**Comment by Towdium** [comment]
Not yet. I'm very busy recently at school. So it might not be fixed very soon. I'm not doing communication actively, but things related to client mode is always tricky because there is much background communication I need to handle. And when it comes to things like world interaction, like #57, it will be more complex. But I will do it ASAP.

**Comment by Towdium** [comment]
I have checked with the official Enigmatica 2 Expert server pack. There is no problem to connect. The issue might be caused by some anti-cheat mechanisms that refuses client mods, or some other mod compatibility issues.
